name: Code Style

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        with:
          php-version: '8.5'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda

      - name: Check code style
        run: composer format-check
